### ISSUE TITLE
Include in examples non-piping versions

### ISSUE THREAD

**Issue by oxinabox** [JuliaFolds/Transducers.jl#199]
I find the examples written using `|>` to be much harder to read.

It would be good to include some using conventional non-piping syntax as well.

**Comment by tkf** [comment]
You mean something like this?

```
xf = compose(
    Partition(7),
    Filter(x -> prod(x) % 11 == 0),
    Cat(),
    Scan(+),
)
```

I am hesitant to include this right now as I am thinking to use something like `∘` instead of `|>` #67 (with long enough deprecation period).  The name of this function would depend on exactly what happens with #67 which in turn depends on https://github.com/JuliaLang/julia/pull/34340.

**Comment by tkf** [comment]
Adding n-ary version for the moment maybe is so bad, though

```
xf = |>(
    Partition(7),
    Filter(x -> prod(x) % 11 == 0),
    Cat(),
    Scan(+),
)
```

**Comment by oxinabox** [comment]
I mean `Map(f)(Filter(g))`
Rather than `Filter(g) |> Map(f)`

(Please tell me you haven't overloaded `l>` directly)

**Comment by tkf** [comment]
I did overload `|>` directly and there are good reasons behind the decision at least at the time I wrote it; e.g., https://discourse.julialang.org/t/ann-transducers-jl-efficient-and-composable-algorithms-for-map-and-reduce-like-operations/19159/13

But as I said in #67, I'm now inclined to remove `|>`. There are still details to fill and they depend on how much help we can get from Julia syntax.

Note that I've never overloaded call operator for transducers. It would be added after `|>` overload is fully removed. So the transition would be done in two phases. It would take sometime until we can do `Map(f)(itr)` _xor_ `Map(f)(rf)`.

**Comment by oxinabox** [comment]
> Note that I've never overloaded call operator for transducers. It would be added after |> overload is fully removed.

Why would it need to be done after `|>` is fully removed?
If it resulted in `Map(f)(Filter(g))` equiv to `Filter(g) |> Map(f)` 
then that would be incredibly confusing.

**Comment by tkf** [comment]
A transducer is a mapping from a reducing function to a reducing function.  It doesn't make sense to define `(::Transducer)(::Transducer) :: Transducer`. It should be `(::Transducer)(::ReducingFunction) :: ReducingFunction` (or the adjoint of it, i.e., `(::Transducer)(::Iterator) :: Iterator`).

`|>` was just a syntax pun. I'm sorry that it confused you.

> If it resulted in `Map(f)(Filter(g))` equiv to `Filter(g) |> Map(f)`
> then that would be incredibly confusing.

This is exactly why `(::Transducer)(::Transducer)` is not defined.

**Comment by oxinabox** [comment]
> `|>` was just a syntax pun. I'm sorry that it  you.

I am confused and scared.

I assumed

`Map(f)(Filter(g))` would be the same as 
`x->Map(f)(Filter(g)(x))`

Is that not the case?  Well I mean it obviously isn't since it's not defined.
But that is the way `Filter(g) |> Map(f)` resolve in my head.
Because it looks like curried functions to me.
So `Map(f)` to me looks like it's the same as `x->Map(f)(x)`
And in a curried language, that means `Map(f)(Filter(g))` would be the same as 
`x->Map(f)(Filter(g)(x))`
since pending arguments always end up at the end.

**Comment by tkf** [comment]
> So `Map(f)` to me looks like it's the same as `x->Map(f)(x)`
> And in a curried language, that means `Map(f)(Filter(g))` would be the same as
> `x->Map(f)(Filter(g)(x))`
> since pending arguments always end up at the end.
> 
> Is this not the right intuition?

That's the correct assumption from the usual `|>` semantics. But Transducer.jl _totally ignores_ it. (This is like DataFrames.jl completely ignores the semantics of `Base.join`. But I'm not saying it's OK for me to do this since others have done the same. As I said, it was a conscious decision taking multiple factors into account.)

`|>` for transducers mean `∘`. This would mean to define `(::Transducer)(::ReducingFunction)` if I were to make `Transducer` a callable (which is not compatible with how `|>` works right now, of course).  But I was afraid that `∘` confuses people too much, because it would looke like `∘` flips the usual order; i.e.,

```juila
Map(f) ∘ Filter(g)
```

would map _then_ filter rather than the opposite order.  With this syntax, `Map(f)(Filter(g)(+))` would mean map, filter, and then, accumulate the elements by `+`.

Note that the elements in the container flow _left-to-right_ in `Map(f) ∘ Filter(g)`. This is the opposite of the way you'd think of how `∘` would work (right-to-left). Using `|>` was my desperate attempt to make it more "user friendly" by hiding this detail.

**Comment by tkf** [comment]
As of Transducers.jl 0.4.39, you _can_ use non-`|>` style `foldl(+, Map(inv)(Filter(isodd)(1:5)))`. See:

https://juliafolds.github.io/Transducers.jl/dev/howto/upgrade-to-ixf/

If you want more native syntax, use `Folds.foldl(+, (inv(x) for x in 1:5 if isodd(x)))` for sequential fold and `Folds.reduce(+, (inv(x) for x in 1:5 if isodd(x)))` or `ThreadsX.reduce(+, (inv(x) for x in 1:5 if isodd(x)))` for parallel fold (ref https://github.com/JuliaFolds/Folds.jl, https://github.com/tkf/ThreadsX.jl).
